import {
  to = segment_reverse_etl_model.id-h52GSGR5TbcZthUf1YmaZp
  id = "h52GSGR5TbcZthUf1YmaZp"
}

resource "segment_reverse_etl_model" "id-h52GSGR5TbcZthUf1YmaZp" {
  description             = " "
  enabled                 = true
  name                    = "dt-test-person-reverseetl-model"
  query                   = "//person info order by the most recent address change after filtering down to the only phone numbers that exist in the stage table\r\nSELECT\tDISTINCT \r\n\t\tEL.EXTERNALLEADID,\r\n\t\tL.PKLEADID AS NEWESTLEADID,\r\n\t\tP.PERSONID,\r\n\t\tP.FIRSTNAME,\r\n\t\tP.LASTNAME,\r\n\t\tP.ISDONOTCONTACT AS PERSONDNC,\r\n\t\tPP.ISDONOTCONTACT AS PHONEDNC,\r\n\t\tPP.ISAUTOMATICCONTACTALLOWED,\r\n\t\tPA.LASTCHANGEDDATETIME,\r\n\t\tPP.PHONENUMBER,\r\n\t\tPA.ZIP5\r\n\t\t//ROW_NUMBER() OVER (PARTITION BY P.PERSONID ORDER BY P.LASTCHANGEDDATETIME DESC) AS PERSONADDRESSNUMBER //THIS IS USED TO GRAB THE MOST RECENTLY UPDATED ADDRESS ZIP5\r\nFROM NON_PROD_REPLICATED.CONTACTSTRATEGY.STAGE_TBLSONARSUPERHOTSECONDPASS AS TSSSP\r\n\tJOIN NON_PROD_REPLICATED.SHAREDDIMENSIONS.DBO_TBLCURRENT_SYSTEM_INFORMATION AS CSI ON CSI.ASOFDATE = TSSSP.ASOFDATE\r\n\tJOIN NON_PROD_REPLICATED.LEADMANAGEMENT.DBO_TBLEXTERNALLEAD AS EL\tON\tEL.EXTERNALLEADID = TSSSP.EXTERNALLEADID\r\n\tJOIN NON_PROD_REPLICATED.LEADMANAGEMENT.DBO_TBLLEAD\t\t\tAS L\tON\tEL.FKLEADID = L.PKLEADID\r\n\tJOIN NON_PROD_REPLICATED.RETAILPERSON.DBO_TBLMASTERPERSON\tAS M\tON\tL.FKMASTERPERSONID = M.MASTERPERSONID\r\n\tJOIN NON_PROD_REPLICATED.RETAILPERSON.DBO_TBLPERSON\t\t\tAS P\tON\tM.PERSONID = P.PERSONID\r\n\tJOIN NON_PROD_REPLICATED.RETAILPERSON.DBO_TBLPERSONADDRESS\tAS PA\tON\tPA.PERSONID = P.PERSONID\r\n\tJOIN NON_PROD_REPLICATED.RETAILPERSON.DBO_TBLPERSONPHONE\tAS PP\tON\tPP.PERSONID = P.PERSONID\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t                    AND\tTSSSP.PHONENUMBER = PP.PHONENUMBER\r\nWHERE   TSSSP.STATUSID = 1\r\nORDER BY P.PERSONID ASC, PA.LASTCHANGEDDATETIME DESC;  "
  query_identifier_column = "EXTERNALLEADID"
  schedule_config         = jsonencode({})
  schedule_strategy       = ""
  source_id               = "ifP3K6J6hzYPxN9wkV48qy"
}