import {
  to = segment_reverse_etl_model.id-orcVAg1DS4JxFjDdr9dPVT
  id = "orcVAg1DS4JxFjDdr9dPVT"
}

resource "segment_reverse_etl_model" "id-orcVAg1DS4JxFjDdr9dPVT" {
  description             = " "
  enabled                 = true
  name                    = "person-phone-data"
  query                   = "SELECT  DISTINCT\n        ROW_NUMBER() OVER(ORDER BY 1) AS ID,\n        MP.PERSONID,\n        COALESCE(P.ISDONOTCONTACT,'FALSE') AS PERSON_DNC,\n        EVENTDATETIME,\n        FORMNAME,\n        F.FIRSTNAME,\n        F.LASTNAME,\n        F.SOCIALSECURITYNUMBER,\n        UUID_STRING('1aae866a-f1a1-3333-9c8d-72a7adae5f67', MD5(F.SOCIALSECURITYNUMBER)) AS USER_ID,\n        F.DATEOFBIRTH,\n        F.PHONENUMBER AS STATED_PHONE,\n        F.PHONENUMBER AS CONTACTABLE_PHONE,\n        COALESCE(PP.ISPREFERRED,'FALSE') AS CONTACTABLE_PHONE_PREFERRED,\n        COALESCE(PP.ISDONOTCONTACT,'FALSE') AS CONTACTABLE_PHONE_DNC,\n        F.EMAILADDRESS AS STATED_EMAIL,\n        F.EMAILADDRESS AS CONTACTABLE_EMAIL,\n        COALESCE(PE.ISPREFERRED,'FALSE') AS CONTACTABLE_EMAIL_PREFERRED,\n        COALESCE(PE.ISDONOTCONTACT,'FALSE') AS CONTACTABLE_EMAIL_DNC,\n        OBJECT_CONSTRUCT('address', COALESCE(address_STREET,'') || ' ' ||  COALESCE(address_CITY,'') || ' ' ||  COALESCE(address_STATE,'') || ' ' || COALESCE(address_ZIP,''))\nFROM MARKETING_RAW.WEBSITE.COSMOS_DATA_FLAT F\nLEFT OUTER JOIN REPLICATED_PROD.RETAILPERSON.DBO_TBLMASTERPERSON MP ON MP.MASTERPERSONID = F.MASTERPERSONID\nLEFT OUTER JOIN REPLICATED_PROD.RETAILPERSON.DBO_TBLPERSON P ON P.PERSONID = MP.PERSONID\nLEFT OUTER JOIN REPLICATED_PROD.RETAILPERSON.DBO_TBLPERSONPHONE PP ON PP.PERSONID = MP.PERSONID AND UPPER(PP.PHONENUMBER) = UPPER(F.PHONENUMBER)\nLEFT OUTER JOIN REPLICATED_PROD.RETAILPERSON.DBO_TBLPERSONEMAIL PE ON PE.PERSONID = MP.PERSONID AND UPPER(PE.EMAILADDRESS) = UPPER(F.EMAILADDRESS)\nWHERE COALESCE(MP.PERSONID, 0) IN (467922,312790)\nORDER BY MP.PERSONID, EVENTDATETIME;"
  query_identifier_column = "ID"
  schedule_config         = jsonencode({})
  schedule_strategy       = ""
  source_id               = "odVaxr3qS5cj8YdWcTj32Z"
}