name: Sync Segment Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Function to Segment
        run: |
          curl -X POST "https://api.segment.io/v1/functions" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.SEGMENT_API_KEY }}" \
          -d @segment-functions/transform-function.js
